version: '3.1'

services:
  postgres:
    image: postgres_17.2
    container_name: postgres_db
    ports:
      -"5432:5432"
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: admin
      - POSTGRES_DB: tiktok_clone
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  - postgres_data: